[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    paulstoffregen/Time@^1.6.1
    file://lib/nnom_core  ; указываем на локальную библиотеку
build_flags = 
    -Wno-narrowing  ; оставляем только этот флаг, пути уже не нужны