; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
;platform = https://github.com/platformio/platform-espressif32.git   ;Fech lastest support for ESP32
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1    ;ESP32-S3
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
; board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.psram_type = opi
upload_speed = 2000000     ;ESP32S3 USB-Serial Converter maximum 2000000bps
upload_port = COM15
monitor_speed = 115200
monitor_port = COM15
debug_tool = esp-builtin
debug_init_break = break app_main
build_type = debug      ;build in debug mode instead of release mode
extra_scripts =
    post:scripts/patch_esp_tflite_micro.py
build_unflags =
    -std=gnu++11
    -std=gnu++14
build_flags =
    -std=gnu++17
  


; build_flags =
;   -std=gnu++17
;   -DCORE_DEBUG_LEVEL=4   ; 0=none 1=error 2=warn 3=info 4=debug 5=verbose
;   ;-DUSE_WEIGHTS_FILE="C:\Users\Artem\Documents\PlatformIO\Projects\Hearing aids ESP32\lib\rnnoise\weights_blob.bin"
; build_unflags =
;   -std=gnu++11
; debug_build_flags = 
;   -std=gnu++17
;   -O0 
;   -g 
;   -ggdb 
;   -DCORE_DEBUG_LEVEL=4   ; 0=none 1=error 2=warn 3=info 4=debug 5=verbose
