#include <Arduino.h>
#include "nnom.h"
#include "weights.h"


// Input/output buffers — sizes must match your model
// Input:  784 floats (28x28 flattened), quantised to int8
// Output: 10 classes
#define INPUT_SIZE  784
#define OUTPUT_SIZE 10

// NNoM works with int8 quantised data
static int8_t input_data[INPUT_SIZE];
static int8_t output_data[OUTPUT_SIZE];

nnom_model_t *model;

// Helper: convert a float array to int8 using the input layer's dec bits
// DENSE_INPUT_OUTPUT_DEC is defined in weights.h by nnom
void float_to_q7(float *src, int8_t *dst, int size, int dec_bits) {
    for (int i = 0; i < size; i++) {
        int32_t val = (int32_t)(src[i] * (1 << dec_bits));
        // Clamp to int8 range
        if (val > 127)  val = 127;
        if (val < -128) val = -128;
        dst[i] = (int8_t)val;
    }
}

// Helper: find the class index with the highest score
int argmax(int8_t *data, int size) {
    int best_idx = 0;
    int8_t best_val = data[0];
    for (int i = 1; i < size; i++) {
        if (data[i] > best_val) {
            best_val = data[i];
            best_idx = i;
        }
    }
    return best_idx;
}

void setup() {
    Serial.begin(115200);
    delay(1000);
    Serial.println("NNoM inference example starting...");

    // Initialise the nnom model from weights.h
    model = nnom_model_create();
    if (model == NULL) {
        Serial.println("ERROR: failed to create model!");
        while (1);
    }

    Serial.println("Model created successfully.");
}

void loop() {
    // --- Prepare dummy input (replace with your real sensor data) ---
    float raw_input[INPUT_SIZE];
    for (int i = 0; i < INPUT_SIZE; i++) {
        raw_input[i] = (float)random(0, 1000) / 1000.0f;  // dummy values in [0, 1]
    }

    // Quantise float input to int8 using the dec bits from weights.h
    // DENSE_INPUT_OUTPUT_DEC is generated by nnom's generate_model()
    float_to_q7(raw_input, input_data, INPUT_SIZE, DENSE_OUTPUT_DEC);

    // Copy quantised input into nnom's input buffer
    memcpy(nnom_input_data, input_data, INPUT_SIZE);

    // --- Run inference ---
    uint32_t start_ms = millis();
    model_run(model);
    uint32_t elapsed_ms = millis() - start_ms;

    // --- Read output ---
    memcpy(output_data, nnom_output_data, OUTPUT_SIZE);

    int predicted_class = argmax(output_data, OUTPUT_SIZE);

    Serial.print("Predicted class: ");
    Serial.print(predicted_class);
    Serial.print("  (inference took ");
    Serial.print(elapsed_ms);
    Serial.println(" ms)");

    // Print raw output scores for debugging
    Serial.print("Scores: ");
    for (int i = 0; i < OUTPUT_SIZE; i++) {
        Serial.print(output_data[i]);
        Serial.print(" ");
    }
    Serial.println();

    delay(2000);
}